project:
  type: rostools-theme
  # TODO: Uncomment if you want to use slides.
  pre-render:
    - quarto render slides/*.qmd
  resources:
    - slides/*.html

book:
  title: "Medical Statistics, MEDMS24B5_1"
  author:
    - name: "Daniel Skak Mahzari-Jensen"
      affiliation: "Aalborg University"
      orcid: "0000-0003-1180-7734"

  date: last-modified
  repo-url: https://github.com/DanMazJen/medicinsk-statistik
  site-url: https://medicinsk-statistik.DanMazJen.org
  body-header: "{{< text_snippet wip >}}" # Comment me out when all website is not actively worked on!
  chapters:
    - index.qmd
    - part: "Overview"
      chapters:
        - overview/syllabus.qmd
        - overview/schedule.qmd
        - overview/learning-design.qmd
    - part: "Pre-course"
      chapters:
        - pre-course/overview.qmd
        - pre-course/reading.qmd
        - pre-course/installing-programs-r.qmd
        - pre-course/r-and-rstudio.qmd
        - pre-course/installing-r-packages.qmd
        - pre-course/code-of-conduct.qmd
        - pre-course/survey.qmd
    - part: "Sessions"
      chapters:
        - sessions/introduction.qmd
        - sessions/session01.qmd
        - sessions/session02.qmd
        - sessions/session03.qmd
        - sessions/session04.qmd
        - sessions/session05.qmd
        - sessions/session06.qmd
        - sessions/session07.qmd
        - sessions/session08.qmd
        - sessions/conclusion.qmd
    - part: "Exercises"
      chapters:
        - exercises/data.qmd
        - exercises/ex01.qmd
        - exercises/ex02.qmd
  appendices:
    - appendix/for-teachers.qmd
    - appendix/references.qmd
    - CHANGELOG.md
    - CONTRIBUTING.md
    - LICENSE.md
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.md
      - text: "Code of Conduct"
        href: "pre-course/code-of-conduct.qmd"

bibliography:
- "includes/references.bib"

format:
  rostools-theme-html:
    theme:
      - brand
    include-before-body:
      - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

metadata-files:
  - _metadata.yml
