project:
  type: rostools-theme
  # TODO: Uncomment if you want to use slides.
  # pre-render:
    # - quarto render slides/*.qmd
  # resources:
  #   - slides/*.html

book:
  title: "Medical Statistics, MEDMS24B5_1"
  author:
    - name: "Daniel Skak Mahzari-Jensen"
      affiliation: "Aalborg University"
      orcid: "test"

  date: last-modified
  repo-url: https://github.com/DanMazJen/medicinsk-statistik
  site-url: https://medicinsk-statistik.DanMazJen.org
  body-header: "{{< text_snippet wip >}}"
  chapters:
    - index.qmd
    - part: "Overview"
      chapters:
        - overview/syllabus.qmd
        - overview/is-this-for-you.qmd
        - overview/schedule.qmd
        - overview/learning-design.qmd
    - part: "Pre-workshop"
      chapters:
        - pre-workshop/overview.qmd
        - pre-workshop/reading.qmd
        - pre-workshop/installing-programs-r.qmd
        - pre-workshop/r-and-rstudio.qmd
        - pre-workshop/installing-r-packages.qmd
        - pre-workshop/code-of-conduct.qmd
        - pre-workshop/survey.qmd
    - part: "Sessions"
      chapters:
        - sessions/introduction.qmd
        - sessions/session01.qmd
        - sessions/session02.qmd
        - sessions/session03.qmd
        - sessions/session04.qmd
        - sessions/session05.qmd
        - sessions/session06.qmd
        - sessions/session07.qmd
        - sessions/session08.qmd
        - sessions/conclusion.qmd
  appendices:
    - appendix/for-teachers.qmd
    - appendix/references.qmd
    - CHANGELOG.md
    - CONTRIBUTING.md
    - LICENSE.md
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.md
      - text: "Code of Conduct"
        href: "pre-workshop/code-of-conduct.qmd"

format:
  rostools-theme-html:
    theme:
      - brand
    include-before-body:
      - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

metadata-files:
  - _metadata.yml
