name: Add to project board

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
  pull_request:
    types:
      - reopened
      - opened

# Limit token permissions for security
permissions: read-all

jobs:
  add-to-project:
    uses: ./.github/workflows/reusable-add-to-project.yml
    # Need write permissions to add PRs to the board
    permissions:
      pull-requests: write
    with:
      board-number: 12
      app-id: ${{ vars.ADD_TO_BOARD_APP_ID }}
    secrets:
      add-to-board-token: ${{ secrets.ADD_TO_BOARD }}
      gh-token: ${{ secrets.GITHUB_TOKEN }}
